### ISSUE TITLE
HTML razmetkada noto'g'ri teg ishlatilishi

### ISSUE THREAD

**Issue by Javohirshakh** [BekzodLolayev/bek-n24#1]
HTML razmetkada noto'g'ri teg ishlatgansiz. Ya'ni footer ni sectionlardagi itemlarning ichiga ishlatgansiz. Bu hech qayerda noto'g'ri deb ko'rsatilmagan bo'lsada, hozirgacha hech qachon bunday tarzda ishlatilganini ko'rmaganim uchun xato deyabman. Lekin footer deb ishlatsa ham bo'ladi adashmasam

![image](https://user-images.githubusercontent.com/77332200/135690576-300d3f81-2018-48fc-bb3e-cf0e1d6cf6d6.png)

**Comment by BekzodLolayev** [comment]
buni videodarslardan ko'rdim, Muhammadjavohir aka ham shunday usulda ishlatgan ekanlar footerni
