### ISSUE TITLE
Matn emas button(yoki link) bo'lishi kerak

### ISSUE THREAD

**Issue by Javohirshakh** [BekzodLolayev/bek-n24#2]
Bu qismda bosilsa yoki boshqa sahifaga o'tishi yoki shu yerga yangi kontentni yuklab berishi kerak. Shu sabab oddiy text emas balki button yoki link bo'lishi kerak

![image](https://user-images.githubusercontent.com/77332200/135690755-2ffe70ad-35a8-464f-8f2f-a70481acda8b.png)

**Comment by BekzodLolayev** [comment]
button bilan almashtirildi
