### ISSUE TITLE
Menu itemlari xato element bilan berilgan

### ISSUE THREAD

**Issue by Javohirshakh** [BekzodLolayev/bek-n24#3]
Menu itemlari a bilan emas li bilan berilgan. 
![image](https://user-images.githubusercontent.com/77332200/135690886-8116facf-7cff-4e7e-829e-4af173b702c7.png)

**Comment by BekzodLolayev** [comment]
<li class="sitenav-item"><a class="sitenav-link" href="#">Главное</a></li> shu tarzda joylab chiqdim
